### ISSUE TITLE
Update to the new/modal version of docsearch UI

### ISSUE THREAD

**Issue by xojotravis** [typesense/typesense-docsearch.js#2]
I'd like to use the updated (modal) version docsearch in front of TypeSense. It looks like work has begun on the 'next' branch here, at least in the React context. I currently use the plain js from jsdelivr but am flexible on how to implement the updated docsearch UI into an existing site. Creating this issue for updates as @jasonbosco mentioned this work is underway now.

**Comment by jasonbosco** [comment]
@xojotravis I just published the new v3 modal layout of Docsearch.js, customized to work with Typesense to npm. Here's how to use it: https://typesense.org/docs/guide/docsearch.html#option-c-custom-docs-framework-with-docsearch-js-v3-modal-layout

Could you give it a shot and let me know how it goes?

**Comment by xojotravis** [comment]
Nice - I will go try it out! Just to confirm from the above doc link is this the right URL for the CSS: https://cdn.jsdelivr.net/npm/@docsearch/css@3 - only asking because the js URL is Typesense specific - perhaps the CSS just doesn't need to be for now.

**Comment by jasonbosco** [comment]
That's right - the CSS URL is not Typesense-specific. I didn't see the need to change the styling Algolia provides.

**Comment by xojotravis** [comment]
First impression = awesome! I'll be updating some parameters and such to adapt to this new format, do some more testing, and circle back in a couple days with an update. Thanks so much for this!

**Comment by xojotravis** [comment]
Quick note - looks like in the v3 docs above that typesenseSearchParams should now be updated to 'typesenseSearchParameters'

**Comment by jasonbosco** [comment]
Ah, good catch. Will push out a fix for it.

**Comment by xojotravis** [comment]
It looks good, and we're going to go live with v3 shortly. I'm going to close my issue here- thank you for your efforts!

**Comment by jasonbosco** [comment]
@xojotravis It turns out the CSS does need to be tweaked slightly (See #3 and #5) to make sure colors match up and to support dark mode. 

I've updated the docs to reflect this: https://github.com/typesense/typesense-website/commit/233fed904b65705cc3847a848e18a2f2d667ad6a
