### ISSUE TITLE
Use page_rank from index to sort results

### ISSUE THREAD

**Issue by aandis** [typesense/typesense-docsearch.js#7]
## Describe the problem

When searching for a document via the [typesense dashboard](https://cloud.typesense.org/clusters/msnl801pkywadxibp/collections/clerky-typesense-search_1677062785/documents/search), I see the documents in the order of the page rank. But when searching the same queries via the [docusaurus search plugin](https://typesense.org/docs/guide/docsearch.html#option-a-docusaurus-powered-sites), I see documents in a different order.

Reticketed from - https://typesense-community.slack.com/archives/C01P749MET0/p1677064398743559

**Comment by aandis** [comment]
cc: @jasonbosco

**Comment by jasonbosco** [comment]
I started looking into this, and I realized that we already do take the `page_rank` field into account in the scraper. 

We use it to calculate an [`item_priority`](https://github.com/typesense/typesense-docsearch-scraper/blob/d83f817a5b9bf6faa1ee2ef190fc1e20d7dda6c2/scraper/src/typesense_helper.py#L94-L97) field for each document, and then [set the `default_sorting_field` to `item_priority`](https://github.com/typesense/typesense-docsearch-scraper/blob/d83f817a5b9bf6faa1ee2ef190fc1e20d7dda6c2/scraper/src/typesense_helper.py#L54). 

So if there is a tie in the text relevance between two documents, then the `item_priority` field is used to break the tie. 

Could you share a screenshot of the exact settings you're using in the Typesense Cloud dashboard and also "copy-as-curl" the network request sent to Typesense from your docs site when you do the same search? We should then be able to compare and see where the difference is coming from.
